name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the release'
        required: true
        default: 'v0.1.0'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build . -t ghcr.io/jckhoe/simple-browser-use:latest
          docker tag ghcr.io/jckhoe/simple-browser-use:latest ghcr.io/jckhoe/simple-browser-use:${{ github.event.inputs.version }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/jckhoe/simple-browser-use:latest
          docker push ghcr.io/jckhoe/simple-browser-use:${{ github.event.inputs.version }}

