
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the release'
        required: true
        default: 'v0.1.0'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and push Docker images (amd64 and arm64)
        run: |
          VERSION=${{ github.event.inputs.version }}

          # Build and push amd64
          docker buildx build --platform linux/amd64 \
            -t ghcr.io/jckhoe/simple-browser-use:latest \
            -t ghcr.io/jckhoe/simple-browser-use:${VERSION} \
            --push .

          # Build and push arm64
          docker buildx build --platform linux/arm64 \
            -t ghcr.io/jckhoe/simple-browser-use:latest-arm \
            -t ghcr.io/jckhoe/simple-browser-use:${VERSION}-arm \
            --push .

